config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  filter :locale

  root 'main#index'

  scope module: 'home' do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get 'login' => 'user_sessions#new', :as => :login

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  end

  scope module: 'dashboard' do
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post 'logout' => 'user_sessions#destroy', :as => :logout

    resources :cards

    resources :blocks do
      member do
        put 'set_as_current'
        put 'reset_as_current'
      end
    end

    put 'review_card' => 'trainer#review_card'
    get 'trainer' => 'trainer#index'

    get 'profile/:id/edit' => 'profile#edit', as: :edit_profile
    put 'profile/:id' => 'profile#update', as: :profile
  end
end

app/views/shared/_alert_notice.slim
- if flash[:alert] || flash[:notice]
  .col-sm-12
    - if flash[:notice]
      .alert.alert-info.alert-dismissible role="alert"
        button.close type="button" data-dismiss="alert" aria-label="Close"
          span aria-hidden="true" &times;
        p#alert= flash[:notice]

    - if flash[:alert]
      .alert.alert-warning.alert-dismissible role="alert"
        button.close type="button" data-dismiss="alert" aria-label="Close"
          span aria-hidden="true" &times;
        p#alert= flash[:alert]

app/views/shared/_header.slim
#header.row
  .col-sm-12
    nav.navbar.navbar-default#header
      .container-fluid
        .navbar-header
          - if current_user
            = link_to t(:flashcards_label), trainer_path, class: "navbar-brand"
          - else
            = link_to t(:flashcards_label), root_path, class: "navbar-brand"

        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          - if current_user
            ul.nav.navbar-nav.navbar-left
              li= link_to t(:all_decks_label), blocks_path
              li= link_to t(:add_deck_label), new_block_path
              li= link_to t(:all_cards_label), cards_path
              li= link_to t(:add_card_label), new_card_path

          p.navbar-text.navbar-right
            - if current_user
              = link_to current_user.email, edit_profile_path(current_user),
                          class: 'user_email'
              = ' | '
              = link_to t(:delete_user_label), user_path(current_user),
                          method: :delete, class: 'navbar-link',
                          data: { confirm: 'Удалить пользователя?' }
              = ' | '
              = link_to t(:log_out_label), :logout, method: :post,
                          class: 'navbar-link'

            - else
              = link_to t(:sing_up_label), new_user_path, class: 'navbar-link'
              = ' | '
              = link_to t(:log_in_with_github_label),
                 auth_at_provider_path(provider: :github), class: 'navbar-link'
              = ' | '
              = link_to t(:log_in_label), :login, class: 'navbar-link'
              = ' | '
              - I18n.available_locales.each do |loc|
                = link_to loc, root_path(user_locale: loc), class: 'navbar-link'
                = ' '